version: '3.8'

services:
  db:
    image: postgres:15
    container_name: motorent-db
    environment:
      POSTGRES_DB: motorentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # painel de administração
    networks:
      - motorent-network

volumes:
  postgres-data:

networks:
  motorent-network:
    driver: bridge